# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mY0kitBbtJXs9PKpZa4OesjWW+e84YTHFupVaUCQ9MGOV/C5kO3gXKvFvY22TDYGwdnfaVidjWuPi8eXc+uAqv+km9V1+E0yxEJYZ/DVQxGYdfii11E/b080qdMpbYhD4M0hea3xh6qSdFLbXbMNpgKp62WzYCYxOj1BnLe1LQmkrgTPqhU/58joAGLJUlZueZQOfN3BG1xVh4CGA3MC978t/BlKS0aXuOKIj4dH2wnV+Cns32veDgbU13C1gexHt3rGdXGSy/xLnLzHHvjtJqJLw9qV/SCaE5LfLixK5qUOO2KWrHr1J5FpqyMAc5diAAqal9ZGjzqDWb3rquDQ+TuDLbbxiOqVIZT9TySd2pnWCkq4E5SAua9v6FZuITv9Qmc0Wzjz0J1rZyZsXMW8yqqlWkBCpkSfbTSxJiyXPMESOS5KQ+J0jHUJNbiBb2iln1PmsKe+bOEz0/WalcNE7kLj9syOVQNGvaSWAdPKrJs+9mvkzIU3w2sHOmZolfFrU8DBCabPqWxtJVAwa5SmmwYl8BXTqvizdTzaYpAs6vtlWiPGNDp0CtBSKhPNlDdR6IHH989H5o1/F+olhuxI+8utc+dKooB98fkuigAIBWblI9Vys6w49UaoqhDkrcc+wvp9eePPsX1ZE3+TZqsBkbTvx/Tw+U95PncGgy5pv9Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
