appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TWOwPZXlL+hUY4Ag2vadXFcHn39+Dl5wGMspg8DAvwTfg1Lq07Sk+AMfanG+uOH3UPj4kys5OdPiH+lTJLgwS+B8fjYv+pil+QbELfVR6KisjlN+j67/9xlnXr0xPmbn3xgjscUZYp/+52f9kxiHPlKFu6px8wCT57mbHmplKg9zD5FcwJd6PXI3kowkJ01I0F8gkEQNPyMZIW3K9KJ8u9bZdJTfrt9wm9wlUX/K8UmKNc0jZ5ibrEmwZPNj+16nK5KOXWZj/DseaMs2FcGLiWsiaBTQXbRAsTZUteuXV9TrBX7YjkaiS6REBdFAvC1Las8GwsI5dbGxwqw4hUY8EwpznAjQzi/flHZBEQhj7ahDkTYwmrlMlrwAz4OtEEVrFxlNbMmbKp5IAz5bdRADHxbz846mn1puWBqCsv0vclKq3yYyJlE8+rrXMl7CYa9ccw/mHpKfRjhw+Ws89U7HvXi8sCcPmyQ47sD5dIcSRnHUvXXlBMSIJ53jQmOwAEM+8Wd3aYTxm9QtcFofRhWPUBBGpXXwx6lMJLy/xJa5PiG6C3RBN2q5J4KCou+Hd5xinGtQ5GzyD4+ECYyOpAq5rw9VVRcMCBQzZpF8bGl4YnaoWN79FsoLkD+a7tKW2mHH0PHzSHcVs4jQJ9BnFaVyumKb+pxUNuvta4b/NHpPv+4=}
